import Head from "next/head"
import styles from './Layout.module.css'

export default function Layout({children, title}) {
  return (
    <>
      <Head>
        <title>Landscape - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, " />
        <link type="image/png" sizes="16x16" rel="icon" href="https://img.icons8.com/color/48/null/pokeball--v1.png" />
      </Head>
      <main className={styles.main}>
        {children}
      </main>
    </>
  )
}